repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-toml
- repo: local
  hooks:
  - id: terraform-fmt
    name: terraform-fmt
    entry: bash -c 'terraform fmt -recursive'
    language: system
    files: \.tf$
  - id: tflint
    name: tflint
    entry: bash -c 'tflint --init && tflint'
    language: system
    files: \.tf$
- repo: https://github.com/terraform-docs/terraform-docs
  rev: v0.20.0
  hooks:
  - id: terraform-docs-go
    args: ["markdown", "table", "--output-file", "README.md", "."]
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.24.2
  hooks:
    - id: gitleaks
- repo: https://github.com/renovatebot/pre-commit-hooks
  rev: 39.263.1
  hooks:
    - id: renovate-config-validator
