name: Pre Commit

on:
  pull_request:
    paths:
      - '**/*'
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - ready_for_review
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - run: git fetch origin
        shell: bash

      - uses: jdx/mise-action@c94f0bf9e520b150e34c017db785461f7e71c5fb # v2.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          cache_save: ${{ github.ref_name == github.event.repository.default_branch }}

      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # 3.0.1
        with:
          extra_args: >
            --from-ref=origin/${{ github.event.pull_request.base.ref }}
            --to-ref=${{ github.event.pull_request.head.sha }}
