name: Trivy Scan

on:
  pull_request:
    paths:
      - '**/*.tf'
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - '**/*.tf'

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # The first call to the action will invoke setup-trivy and install trivy
      - name: Generate Trivy Vulnerability Report
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # v0.30.0
        with:
          scan-type: "fs"
          scan-ref: .
          severity: "CRITICAL,HIGH"
          scanners: "misconfig,secret,vuln"
          format: "sarif"
          output: "trivy-results.sarif"
          exit-code: 0

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@ff0a06e83cb2de871e5a09832bc6a81e7276941f # v3.28.18
        with:
          sarif_file: "trivy-results.sarif"
